### ISSUE TITLE
code is not working

### ISSUE THREAD

**Issue by ap78699** [dhruv-kun/whatsapp-automation#2]
its showing a error
Traceback (most recent call last):
  File "C:\Users\ABHINAV\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\ABHINAV\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\ABHINAV\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ABHINAV\Desktop\-automation\main.py", line 360, in main
    driver = login()
  File "C:\Users\ABHINAV\Desktop\-automation\main.py", line 201, in login
    driver = webdriver.Chrome(chrome_path)
  File "C:\Users\ABHINAV\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\Users\ABHINAV\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ABHINAV\Desktop\-automation\main.py", line 416, in <module>
    main()
  File "C:\Users\ABHINAV\Desktop\-automation\main.py", line 412, in main
    logout(driver)
UnboundLocalError: local variable 'driver' referenced before assignment
>>>

**Comment by dhruv-kun** [comment]
Sorry for this much delay in reply. 
You have to download the chromedriver first and place it in the code directory to run this script.
